package com.santhosh.accounts.entity;
// Generated Oct 1, 2016 4:48:28 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountHolder generated by hbm2java
 */
@Entity
@Table(name = "account_holder", catalog = "accountmanagement")
public class AccountHolder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer accountHolderId;
	private String accountHolderName;
	private Date createdTime;
	private Date updatedTime;
	//private Set<Account> accounts = new HashSet<Account>(0);

	public AccountHolder() {
	}

	public AccountHolder(String accountHolderName) {
		this.accountHolderName = accountHolderName;
	}

	/*public AccountHolder(String accountHolderName, Date createdTime, Date updatedTime, Set<Account> accounts) {
		this.accountHolderName = accountHolderName;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.accounts = accounts;
	}*/
	
	public AccountHolder(String accountHolderName, Date createdTime, Date updatedTime) {
		this.accountHolderName = accountHolderName;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "account_holder_id", unique = true, nullable = false)
	public Integer getAccountHolderId() {
		return this.accountHolderId;
	}

	public void setAccountHolderId(Integer accountHolderId) {
		this.accountHolderId = accountHolderId;
	}

	@Column(name = "account_holder_name", nullable = false)
	public String getAccountHolderName() {
		return this.accountHolderName;
	}

	public void setAccountHolderName(String accountHolderName) {
		this.accountHolderName = accountHolderName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/*@OneToMany(fetch = FetchType.EAGER, mappedBy = "accountHolder")
	public Set<Account> getAccounts() {
		return this.accounts;
	}*/

/*	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}
*/
}
